# Generated by Django 3.1.2 on 2020-10-15 08:07

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='正文'),
        ),
    ]
