# Generated by Django 3.1.2 on 2020-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20201015_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='开启评论'),
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(default=1, verbose_name='摘要'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_time',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=True, verbose_name='发布'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
    ]
